In [3]:
from pathlib import Path
import numpy as np
import pandas as pd

In [4]:
PROJECT_ROOT = Path("..")
RAW_DATA = PROJECT_ROOT / "data" / "raw"

In [5]:
customers = pd.read_csv(RAW_DATA / "olist_customers_dataset.csv")
orders = pd.read_csv(RAW_DATA / "olist_orders_dataset.csv")
order_items = pd.read_csv(RAW_DATA / "olist_order_items_dataset.csv")
payments = pd.read_csv(RAW_DATA / "olist_order_payments_dataset.csv")
reviews = pd.read_csv(RAW_DATA / "olist_order_reviews_dataset.csv")
products = pd.read_csv(RAW_DATA / "olist_products_dataset.csv")
sellers = pd.read_csv(RAW_DATA / "olist_sellers_dataset.csv")
geolocation = pd.read_csv(RAW_DATA / "olist_geolocation_dataset.csv")
categories = pd.read_csv(RAW_DATA / "product_category_name_translation.csv")

In [6]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "geolocation": geolocation,
    "categories": categories,
}

In [7]:
def profile_table(df):
    """Return a summary profile for a DataFrame."""

    profile = pd.DataFrame({
        "Data Type": df.dtypes.astype(str),
        "Missing Values": df.isnull().sum(),
        "Missing %": (df.isnull().mean() * 100).round(2),
        "Unique Values": df.nunique(),
    })

    return profile

In [9]:
profile_table(customers)

                         Data Type  Missing Values  Missing %  Unique Values
customer_id                    str               0        0.0          99441
customer_unique_id             str               0        0.0          96096
customer_zip_code_prefix     int64               0        0.0          14994
customer_city                  str               0        0.0           4119
customer_state                 str               0        0.0             27

In [8]:
summary = []

for name, df in datasets.items():

    summary.append({
        "Table": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Duplicates": df.duplicated().sum(),
        "Memory (MB)": round(df.memory_usage(deep=True).sum()/1024**2,2)
    })

summary = pd.DataFrame(summary)

summary

         Table     Rows  Columns  Duplicates  Memory (MB)
0    customers    99441        5           0        26.59
1       orders    99441        8           0        52.94
2  order_items   112650        7           0        35.99
3     payments   103886        5           0        16.23
4      reviews    99224        7           0        39.12
5     products    32951        9           0         6.30
6      sellers     3095        4           0         0.59
7  geolocation  1000163        5      261831       130.26
8   categories       71        2           0         0.01