In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

In [2]:
PROJECT_ROOT = Path("..")
RAW_DATA = PROJECT_ROOT / "data" / "raw"

In [3]:
customers = pd.read_csv(RAW_DATA / "olist_customers_dataset.csv")
orders = pd.read_csv(RAW_DATA / "olist_orders_dataset.csv")
order_items = pd.read_csv(RAW_DATA / "olist_order_items_dataset.csv")
payments = pd.read_csv(RAW_DATA / "olist_order_payments_dataset.csv")
reviews = pd.read_csv(RAW_DATA / "olist_order_reviews_dataset.csv")
products = pd.read_csv(RAW_DATA / "olist_products_dataset.csv")
sellers = pd.read_csv(RAW_DATA / "olist_sellers_dataset.csv")
geolocation = pd.read_csv(RAW_DATA / "olist_geolocation_dataset.csv")
categories = pd.read_csv(RAW_DATA / "product_category_name_translation.csv")

In [4]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "geolocation": geolocation,
    "categories": categories,
}

In [5]:
def quality_summary(df):
    """
    Returns a data quality summary for a dataframe.
    """

    summary = pd.DataFrame({
        "Data Type": df.dtypes.astype(str),
        "Missing Values": df.isnull().sum(),
        "Missing %": (df.isnull().mean()*100).round(2),
        "Unique Values": df.nunique()
    })

    return summary

In [6]:
for name, df in datasets.items():

    print("=" * 80)
    print(name.upper())
    print("=" * 80)

    display(quality_summary(df))

================================================================================
CUSTOMERS
================================================================================

                         Data Type  Missing Values  Missing %  Unique Values
customer_id                    str               0        0.0          99441
customer_unique_id             str               0        0.0          96096
customer_zip_code_prefix     int64               0        0.0          14994
customer_city                  str               0        0.0           4119
customer_state                 str               0        0.0             27

================================================================================
ORDERS
================================================================================

,Data Type,Missing Values,Missing %,Unique Values
order_id,str,0,0.00,99441
customer_id,str,0,0.00,99441
order_status,str,0,0.00,8
order_purchase_timestamp,str,0,0.00,98875
order_approved_at,str,160,0.16,90733
order_delivered_carrier_date,str,1783,1.79,81018
order_delivered_customer_date,str,2965,2.98,95664
order_estimated_delivery_date,str,0,0.00,459

================================================================================
ORDER_ITEMS
================================================================================

                    Data Type  Missing Values  Missing %  Unique Values
order_id                  str               0        0.0          98666
order_item_id           int64               0        0.0             21
product_id                str               0        0.0          32951
seller_id                 str               0        0.0           3095
shipping_limit_date       str               0        0.0          93318
price                 float64               0        0.0           5968
freight_value         float64               0        0.0           6999

================================================================================
PAYMENTS
================================================================================

                     Data Type  Missing Values  Missing %  Unique Values
order_id                   str               0        0.0          99440
payment_sequential       int64               0        0.0             29
payment_type               str               0        0.0              5
payment_installments     int64               0        0.0             24
payment_value          float64               0        0.0          29077

================================================================================
REVIEWS
================================================================================

                        Data Type  Missing Values  Missing %  Unique Values
review_id                     str               0       0.00          98410
order_id                      str               0       0.00          98673
review_score                int64               0       0.00              5
review_comment_title          str           87656      88.34           4527
review_comment_message        str           58247      58.70          36159
review_creation_date          str               0       0.00            636
review_answer_timestamp       str               0       0.00          98248

================================================================================
PRODUCTS
================================================================================

                           Data Type  Missing Values  Missing %  Unique Values
product_id                       str               0       0.00          32951
product_category_name            str             610       1.85             73
product_name_lenght          float64             610       1.85             66
product_description_lenght   float64             610       1.85           2960
product_photos_qty           float64             610       1.85             19
product_weight_g             float64               2       0.01           2204
product_length_cm            float64               2       0.01             99
product_height_cm            float64               2       0.01            102
product_width_cm             float64               2       0.01             95

================================================================================
SELLERS
================================================================================

                       Data Type  Missing Values  Missing %  Unique Values
seller_id                    str               0        0.0           3095
seller_zip_code_prefix     int64               0        0.0           2246
seller_city                  str               0        0.0            611
seller_state                 str               0        0.0             23

================================================================================
GEOLOCATION
================================================================================

,Data Type,Missing Values,Missing %,Unique Values
geolocation_zip_code_prefix,int64,0,0.0,19015
geolocation_lat,float64,0,0.0,717360
geolocation_lng,float64,0,0.0,717613
geolocation_city,str,0,0.0,8011
geolocation_state,str,0,0.0,27

================================================================================
CATEGORIES
================================================================================

,Data Type,Missing Values,Missing %,Unique Values
product_category_name,str,0,0.0,71
product_category_name_english,str,0,0.0,71

In [7]:
print("PRIMARY KEY VALIDATION\n")

print(f"Customers : {customers['customer_id'].duplicated().sum()} duplicates")

print(f"Orders : {orders['order_id'].duplicated().sum()} duplicates")

print(f"Products : {products['product_id'].duplicated().sum()} duplicates")

print(f"Sellers : {sellers['seller_id'].duplicated().sum()} duplicates")

print(f"Reviews : {reviews['review_id'].duplicated().sum()} duplicates")

print(
    "Order Items :",
    order_items.duplicated(
        subset=["order_id", "order_item_id"]
    ).sum(),
    "duplicates",
)

PRIMARY KEY VALIDATION

Customers : 0 duplicates
Orders : 0 duplicates
Products : 0 duplicates
Sellers : 0 duplicates
Reviews : 814 duplicates
Order Items : 0 duplicates

In [8]:
print("FOREIGN KEY VALIDATION\n")

missing_customers = (
    ~orders["customer_id"].isin(customers["customer_id"])
).sum()

missing_products = (
    ~order_items["product_id"].isin(products["product_id"])
).sum()

missing_sellers = (
    ~order_items["seller_id"].isin(sellers["seller_id"])
).sum()

missing_orders_payment = (
    ~payments["order_id"].isin(orders["order_id"])
).sum()

missing_orders_review = (
    ~reviews["order_id"].isin(orders["order_id"])
).sum()

print("Missing Customers :", missing_customers)
print("Missing Products :", missing_products)
print("Missing Sellers :", missing_sellers)
print("Missing Orders (Payments) :", missing_orders_payment)
print("Missing Orders (Reviews) :", missing_orders_review)

FOREIGN KEY VALIDATION

Missing Customers : 0
Missing Products : 0
Missing Sellers : 0
Missing Orders (Payments) : 0
Missing Orders (Reviews) : 0

In [9]:
for name, df in datasets.items():

    print("=" * 70)
    print(name.upper())

    missing = (
        df.isnull()
          .sum()
          .sort_values(ascending=False)
    )

    missing = missing[missing > 0]

    if len(missing) == 0:
        print("No missing values\n")

    else:
        display(missing)

======================================================================
CUSTOMERS
No missing values

======================================================================
ORDERS

order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
dtype: int64

======================================================================
ORDER_ITEMS
No missing values

======================================================================
PAYMENTS
No missing values

======================================================================
REVIEWS

review_comment_title      87656
review_comment_message    58247
dtype: int64

======================================================================
PRODUCTS

product_category_name         610
product_description_lenght    610
product_name_lenght           610
product_photos_qty            610
product_weight_g                2
product_height_cm               2
product_length_cm               2
product_width_cm                2
dtype: int64

======================================================================
SELLERS
No missing values

======================================================================
GEOLOCATION
No missing values

======================================================================
CATEGORIES
No missing values

In [10]:
duplicates = []

for name, df in datasets.items():

    duplicates.append({
        "Dataset": name,
        "Duplicate Rows": df.duplicated().sum()
    })

duplicates = pd.DataFrame(duplicates)

duplicates

       Dataset  Duplicate Rows
0    customers               0
1       orders               0
2  order_items               0
3     payments               0
4      reviews               0
5     products               0
6      sellers               0
7  geolocation          261831
8   categories               0

In [11]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [14]:
print("Earliest Purchase")

print(orders["order_purchase_timestamp"].min())

print()

print("Latest Purchase")

print(orders["order_purchase_timestamp"].max())

Earliest Purchase
2016-09-04 21:15:19

Latest Purchase
2018-10-17 17:30:18

In [15]:
print(
    "Negative Prices:",
    (order_items["price"] < 0).sum()
)

Negative Prices: 0

In [16]:
print(
    "Negative Freight:",
    (order_items["freight_value"] < 0).sum()
)

Negative Freight: 0

In [17]:
print(
    "Negative Payments:",
    (payments["payment_value"] < 0).sum()
)

Negative Payments: 0

In [18]:
print(
    sorted(reviews["review_score"].unique())
)

[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [19]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [20]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [21]:
products["product_category_name"].value_counts().head(20)

product_category_name
cama_mesa_banho                      3029
esporte_lazer                        2867
moveis_decoracao                     2657
beleza_saude                         2444
utilidades_domesticas                2335
automotivo                           1900
informatica_acessorios               1639
brinquedos                           1411
relogios_presentes                   1329
telefonia                            1134
bebes                                 919
perfumaria                            868
papelaria                             849
fashion_bolsas_e_acessorios           849
cool_stuff                            789
ferramentas_jardim                    753
pet_shop                              719
eletronicos                           517
construcao_ferramentas_construcao     400
eletrodomesticos                      370
Name: count, dtype: int64

In [22]:
sellers["seller_state"].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
AC       1
PI       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

In [23]:
customers["customer_state"].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64